---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: managedprojects-monitor
  labels:
    app: managedprojects-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: managedprojects-monitor
  template:
    metadata:
      labels:
        app: managedprojects-monitor
    spec:
      containers:
      - name: managedprojects-monitor
        image: "quay.io/sergioperez/managedprojects-monitor:v0.0.5"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 60
